language: node_js

node_js:
 - "node"

branches:
  only:
    - source

cache:
  npm: true
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist
  target-branch: master
