language: node_js

node_js:
 - "node"

branches:
  only:
    - master

cache:
  npm: true
  directories:
    - node_modules

jobs:
  include:
    - stage: build
      script: npm run build && ./deploy.sh
